#!/bin/bash

VAR="123txt543"

if echo "$VAR" | grep -q txt  # if [[ $VAR = *txt* ]]
then
  echo "$VAR contains the substring sequence \"txt\""
fi

a=`echo "HELLO" | tr A-Z a-z` # echo, in combination with command substitution
                              # can set a variable

# echo `command` deletes any linefeeds, generated by command
# compare:
ls -l /tmp
echo `ls -l /tmp` # no '\n' between files
